name: Python_pipe

on:
  push:
    branches:
      - master

jobs:
  checkstyle_project:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone repo
        uses: actions/checkout@v1

      - name: Set version Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.12.2'

      - name: Install dependencies python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check style project
        continue-on-error: true
        run: |
          pip install pycodestyle
          pycodestyle .

